<section class="py-14 overflow-hidden">
    <div class="container">
        <div class="flex flex-wrap -mx-4">
            <div class="w-full px-4">
                <div class="max-w-[770px] mx-auto mb-[60px] text-center">
                    <h2
                        class="
                  font-bold
                  text-3xl
                  md:text-4xl
                  xl:text-[45px]
                  leading-tight
                  md:leading-tight
                  xl:leading-tight
                  text-main text-center
                  mb-3
                "
                    >
                        More information
                    </h2>
                    <p
                        class="
                  font-medium
                  text-base
                  md:text-lg
                  text-body-color
                  leading-relaxed
                  md:leading-relaxed
                "
                    >
                        Start grasping the full potential of mobile. Today!
                    </p>
                </div>
            </div>
        </div>

        <div class="flex -mx-4">
            <div class="w-full px-4">
                <div
                    class="
                bg-white
                max-w-[770px]
                w-full
                mx-auto
                py-10
                px-6
                sm:py-[60px] sm:px-[65px]
                md:p-10
                lg:py-[60px] lg:px-[65px]
                shadow-card
                shadow-main
                border border-form-stroke
                relative
              "
                >
                    <form>
                        <div class="flex flex-wrap -mx-4">
                            <div class="w-full md:w-1/2 px-4">
                                <div class="mb-7">
                                    <label
                                        for="firstName"
                                        class="font-medium text-base mb-3 block text-dark"
                                    >
                                        First Name
                                    </label>
                                    <input
                                        id="firstName"
                                        type="text"
                                        name="firstName"
                                        placeholder="Enter your first name"
                                        class="
                          w-full
                          bg-white
                          border border-form-stroke
                          border-stroke-main
                          py-4
                          px-6
                          placeholder-[#9699A6]
                          focus:border-main
                          outline-none
                          shadow-input
                        "
                                    />
                                </div>
                            </div>
                            <div class="w-full md:w-1/2 px-4">
                                <div class="mb-7">
                                    <label
                                        for="lastName"
                                        class="font-medium text-base mb-3 block text-dark"
                                    >
                                        Last Name
                                    </label>
                                    <input
                                        id="lastName"
                                        type="text"
                                        name="lastName"
                                        placeholder="Enter your last Name"
                                        class="
                          w-full
                          bg-white
                          border border-form-stroke
                          py-4
                          px-6
                          placeholder-[#9699A6]
                          focus:border-main
                          outline-none
                          shadow-input
                        "
                                    />
                                </div>
                            </div>
                            <div class="w-full md:w-1/2 px-4">
                                <div class="mb-7">
                                    <label
                                        for="email"
                                        class="font-medium text-base mb-3 block text-dark"
                                    >
                                        Business Email
                                    </label>
                                    <input
                                        id="email"
                                        type="email"
                                        name="email"
                                        placeholder="Enter your Email"
                                        class="
                          w-full
                          bg-white
                          border border-form-stroke
                          py-4
                          px-6
                          placeholder-[#9699A6]
                          focus:border-main
                          outline-none
                          shadow-input
                        "
                                    />
                                </div>
                            </div>
                            <div class="w-full md:w-1/2 px-4">
                                <div class="mb-7">
                                    <label
                                        for="number"
                                        class="font-medium text-base mb-3 block text-dark"
                                    >
                                        Phone number
                                    </label>
                                    <input
                                        id="number"
                                        type="text"
                                        name="number"
                                        placeholder="Enter your number"
                                        class="
                          w-full
                          bg-white
                          border border-form-stroke
                          py-4
                          px-6
                          placeholder-[#9699A6]
                          focus:border-main
                          outline-none
                          shadow-input
                        "
                                    />
                                </div>
                            </div>
                            <div class="w-full px-4">
                                <div class="mb-7">
                                    <label
                                        for="message"
                                        class="font-medium text-base mb-3 block text-dark"
                                    >
                                        Website
                                    </label>
                                    <input
                                        id="message"
                                        name="message"
                                        placeholder="Type your Website URL"
                                        type="url"
                                        class="
                          w-full
                          bg-white
                          border
                          py-4
                          px-6
                          resize-none
                          placeholder-[#9699A6]
                          focus:border-main
                          outline-none
                          shadow-input
                        "
                                    >
                                </div>
                            </div>

                            <div class="w-full px-4">
                                <div class="text-center">
                                    <button
                                        type="submit"
                                        class="
                          inline-flex
                          items-center
                          justify-center
                          text-base
                          font-semibold
                          py-3
                          px-10
                          text-white
                          rounded-lg
                          bg-main
                          border-2 border-main
                          hover:bg-opacity-90
                        "
                                    >
                                        More Information
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>

                    <div>
                <span class="absolute -top-5 -right-5 -z-10">
                  <svg
                      width="57"
                      height="121"
                      viewBox="0 0 57 121"
                      fill="#a10000"
                      xmlns="http://www.w3.org/2000/svg"
                  >
                    <circle
                        cx="23.0992"
                        cy="1.62854"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="12.3649"
                        cy="1.62854"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="1.62854"
                        cy="1.62854"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="23.0992"
                        cy="12.3864"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="12.3649"
                        cy="12.3864"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="1.62854"
                        cy="12.3864"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="23.0992"
                        cy="23.1422"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="12.3649"
                        cy="23.1422"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="1.62854"
                        cy="23.1422"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="23.0992"
                        cy="33.9005"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="12.3649"
                        cy="33.9005"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="1.62854"
                        cy="33.9005"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="23.0992"
                        cy="44.6515"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="12.3649"
                        cy="44.6515"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="1.62854"
                        cy="44.6515"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="23.0992"
                        cy="55.4049"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="12.3649"
                        cy="55.4049"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="1.62854"
                        cy="55.4049"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="23.0992"
                        cy="66.1559"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="23.0992"
                        cy="76.6744"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="23.0992"
                        cy="87.193"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="23.0992"
                        cy="97.7111"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="23.0992"
                        cy="108.227"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="23.0992"
                        cy="118.746"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="12.3629"
                        cy="66.1559"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="12.3629"
                        cy="76.6744"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="12.3629"
                        cy="87.193"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="12.3629"
                        cy="97.7111"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="12.3629"
                        cy="108.227"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="12.3629"
                        cy="118.746"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="1.62854"
                        cy="66.1559"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="1.62854"
                        cy="76.6744"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="1.62854"
                        cy="87.193"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="1.62854"
                        cy="97.7111"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="1.62854"
                        cy="108.227"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="1.62854"
                        cy="118.746"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="33.8571"
                        cy="1.62854"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="33.8571"
                        cy="12.3864"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="33.8571"
                        cy="23.1422"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="33.8571"
                        cy="33.9005"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="33.8571"
                        cy="44.6515"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="33.8571"
                        cy="55.4049"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="33.8571"
                        cy="66.1559"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="33.8571"
                        cy="76.6744"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="33.8571"
                        cy="87.193"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="33.8571"
                        cy="97.7111"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="33.8571"
                        cy="108.227"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="33.8571"
                        cy="118.746"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="44.6149"
                        cy="1.62854"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="44.6149"
                        cy="12.3864"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="44.6149"
                        cy="23.1422"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="44.6149"
                        cy="33.9005"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="44.6149"
                        cy="44.6515"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="44.6149"
                        cy="55.4049"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="44.6149"
                        cy="66.1559"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="44.6149"
                        cy="76.6744"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="44.6149"
                        cy="87.193"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="44.6149"
                        cy="97.7111"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="44.6149"
                        cy="108.227"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="44.6149"
                        cy="118.746"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="55.3707"
                        cy="1.62854"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="55.3707"
                        cy="12.3864"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="55.3707"
                        cy="23.1422"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="55.3707"
                        cy="33.9005"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="55.3707"
                        cy="44.6515"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="55.3707"
                        cy="55.4049"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="55.3707"
                        cy="66.1559"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="55.3707"
                        cy="76.6744"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="55.3707"
                        cy="87.193"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="55.3707"
                        cy="97.7111"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="55.3707"
                        cy="108.227"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="55.3707"
                        cy="118.746"
                        r="1.62854"
                        fill="#a10000"
                    />
                  </svg>
                </span>

                        <span class="absolute -bottom-5 -left-5 -z-10">
                  <svg
                      width="57"
                      height="121"
                      viewBox="0 0 57 121"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                  >
                    <circle
                        cx="23.0992"
                        cy="1.62854"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="12.3649"
                        cy="1.62854"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="1.62854"
                        cy="1.62854"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="23.0992"
                        cy="12.3864"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="12.3649"
                        cy="12.3864"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="1.62854"
                        cy="12.3864"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="23.0992"
                        cy="23.1422"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="12.3649"
                        cy="23.1422"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="1.62854"
                        cy="23.1422"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="23.0992"
                        cy="33.9005"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="12.3649"
                        cy="33.9005"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="1.62854"
                        cy="33.9005"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="23.0992"
                        cy="44.6515"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="12.3649"
                        cy="44.6515"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="1.62854"
                        cy="44.6515"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="23.0992"
                        cy="55.4049"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="12.3649"
                        cy="55.4049"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="1.62854"
                        cy="55.4049"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="23.0992"
                        cy="66.1559"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="23.0992"
                        cy="76.6744"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="23.0992"
                        cy="87.193"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="23.0992"
                        cy="97.7111"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="23.0992"
                        cy="108.227"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="23.0992"
                        cy="118.746"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="12.3629"
                        cy="66.1559"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="12.3629"
                        cy="76.6744"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="12.3629"
                        cy="87.193"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="12.3629"
                        cy="97.7111"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="12.3629"
                        cy="108.227"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="12.3629"
                        cy="118.746"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="1.62854"
                        cy="66.1559"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="1.62854"
                        cy="76.6744"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="1.62854"
                        cy="87.193"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="1.62854"
                        cy="97.7111"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="1.62854"
                        cy="108.227"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="1.62854"
                        cy="118.746"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="33.8571"
                        cy="1.62854"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="33.8571"
                        cy="12.3864"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="33.8571"
                        cy="23.1422"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="33.8571"
                        cy="33.9005"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="33.8571"
                        cy="44.6515"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="33.8571"
                        cy="55.4049"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="33.8571"
                        cy="66.1559"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="33.8571"
                        cy="76.6744"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="33.8571"
                        cy="87.193"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="33.8571"
                        cy="97.7111"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="33.8571"
                        cy="108.227"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="33.8571"
                        cy="118.746"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="44.6149"
                        cy="1.62854"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="44.6149"
                        cy="12.3864"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="44.6149"
                        cy="23.1422"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="44.6149"
                        cy="33.9005"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="44.6149"
                        cy="44.6515"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="44.6149"
                        cy="55.4049"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="44.6149"
                        cy="66.1559"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="44.6149"
                        cy="76.6744"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="44.6149"
                        cy="87.193"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="44.6149"
                        cy="97.7111"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="44.6149"
                        cy="108.227"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="44.6149"
                        cy="118.746"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="55.3707"
                        cy="1.62854"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="55.3707"
                        cy="12.3864"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="55.3707"
                        cy="23.1422"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="55.3707"
                        cy="33.9005"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="55.3707"
                        cy="44.6515"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="55.3707"
                        cy="55.4049"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="55.3707"
                        cy="66.1559"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="55.3707"
                        cy="76.6744"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="55.3707"
                        cy="87.193"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="55.3707"
                        cy="97.7111"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="55.3707"
                        cy="108.227"
                        r="1.62854"
                        fill="#a10000"
                    />
                    <circle
                        cx="55.3707"
                        cy="118.746"
                        r="1.62854"
                        fill="#a10000"
                    />
                  </svg>
                </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
